#!/bin/bash
LINTVER="1.16.0"
LINTCMD="golangci-lint"
if [ "${CI}" ]; then
    curl -LO https://github.com/golangci/golangci-lint/releases/download/v${LINTVER}/golangci-lint-${LINTVER}-linux-amd64.tar.gz
    tar -zxvf golangci-lint-${LINTVER}-linux-amd64.tar.gz
    LINTCMD="./golangci-lint-1.16.0-linux-amd64/golangci-lint"
else
    go get github.com/golangci/golangci-lint/cmd/golangci-lint
fi
${LINTCMD} run
